export interface Location { city: string; country: string }

export const POPULAR_LOCATIONS: Location[] = [
  // Europe
  { city: 'Warsaw',          country: 'Poland' },
  { city: 'Krakow',          country: 'Poland' },
  { city: 'Paris',           country: 'France' },
  { city: 'Lyon',            country: 'France' },
  { city: 'Berlin',          country: 'Germany' },
  { city: 'Munich',          country: 'Germany' },
  { city: 'London',          country: 'United Kingdom' },
  { city: 'Manchester',      country: 'United Kingdom' },
  { city: 'Rome',            country: 'Italy' },
  { city: 'Milan',           country: 'Italy' },
  { city: 'Madrid',          country: 'Spain' },
  { city: 'Barcelona',       country: 'Spain' },
  { city: 'Amsterdam',       country: 'Netherlands' },
  { city: 'Brussels',        country: 'Belgium' },
  { city: 'Vienna',          country: 'Austria' },
  { city: 'Prague',          country: 'Czech Republic' },
  { city: 'Budapest',        country: 'Hungary' },
  { city: 'Bucharest',       country: 'Romania' },
  { city: 'Sofia',           country: 'Bulgaria' },
  { city: 'Athens',          country: 'Greece' },
  { city: 'Lisbon',          country: 'Portugal' },
  { city: 'Stockholm',       country: 'Sweden' },
  { city: 'Oslo',            country: 'Norway' },
  { city: 'Copenhagen',      country: 'Denmark' },
  { city: 'Helsinki',        country: 'Finland' },
  { city: 'Dublin',          country: 'Ireland' },
  { city: 'Zurich',          country: 'Switzerland' },
  { city: 'Bern',            country: 'Switzerland' },
  { city: 'Kyiv',            country: 'Ukraine' },
  { city: 'Moscow',          country: 'Russia' },
  { city: 'St. Petersburg',  country: 'Russia' },
  { city: 'Belgrade',        country: 'Serbia' },
  { city: 'Zagreb',          country: 'Croatia' },
  { city: 'Ljubljana',       country: 'Slovenia' },
  { city: 'Bratislava',      country: 'Slovakia' },
  { city: 'Vilnius',         country: 'Lithuania' },
  { city: 'Riga',            country: 'Latvia' },
  { city: 'Tallinn',         country: 'Estonia' },
  { city: 'Minsk',           country: 'Belarus' },
  { city: 'Chisinau',        country: 'Moldova' },
  { city: 'Tirana',          country: 'Albania' },
  { city: 'Sarajevo',        country: 'Bosnia' },
  { city: 'Skopje',          country: 'North Macedonia' },
  { city: 'Podgorica',       country: 'Montenegro' },
  { city: 'Reykjavik',       country: 'Iceland' },
  { city: 'Luxembourg',      country: 'Luxembourg' },
  { city: 'Valletta',        country: 'Malta' },
  { city: 'Nicosia',         country: 'Cyprus' },
  // Americas
  { city: 'New York',        country: 'USA' },
  { city: 'Los Angeles',     country: 'USA' },
  { city: 'Chicago',         country: 'USA' },
  { city: 'Houston',         country: 'USA' },
  { city: 'Washington',      country: 'USA' },
  { city: 'Miami',           country: 'USA' },
  { city: 'San Francisco',   country: 'USA' },
  { city: 'Seattle',         country: 'USA' },
  { city: 'Boston',          country: 'USA' },
  { city: 'Dallas',          country: 'USA' },
  { city: 'Queens',          country: 'USA' },
  { city: 'Ottawa',          country: 'Canada' },
  { city: 'Toronto',         country: 'Canada' },
  { city: 'Vancouver',       country: 'Canada' },
  { city: 'Montreal',        country: 'Canada' },
  { city: 'Mexico City',     country: 'Mexico' },
  { city: 'Guadalajara',     country: 'Mexico' },
  { city: 'Brasilia',        country: 'Brazil' },
  { city: 'São Paulo',       country: 'Brazil' },
  { city: 'Rio de Janeiro',  country: 'Brazil' },
  { city: 'Buenos Aires',    country: 'Argentina' },
  { city: 'Santiago',        country: 'Chile' },
  { city: 'Bogota',          country: 'Colombia' },
  { city: 'Lima',            country: 'Peru' },
  { city: 'Caracas',         country: 'Venezuela' },
  { city: 'Havana',          country: 'Cuba' },
  { city: 'Panama City',     country: 'Panama' },
  { city: 'San José',        country: 'Costa Rica' },
  { city: 'Quito',           country: 'Ecuador' },
  { city: 'La Paz',          country: 'Bolivia' },
  { city: 'Asuncion',        country: 'Paraguay' },
  { city: 'Montevideo',      country: 'Uruguay' },
  // Asia
  { city: 'Beijing',         country: 'China' },
  { city: 'Shanghai',        country: 'China' },
  { city: 'Guangzhou',       country: 'China' },
  { city: 'Tokyo',           country: 'Japan' },
  { city: 'Osaka',           country: 'Japan' },
  { city: 'Seoul',           country: 'South Korea' },
  { city: 'Busan',           country: 'South Korea' },
  { city: 'New Delhi',       country: 'India' },
  { city: 'Mumbai',          country: 'India' },
  { city: 'Bangalore',       country: 'India' },
  { city: 'Chennai',         country: 'India' },
  { city: 'Kolkata',         country: 'India' },
  { city: 'Islamabad',       country: 'Pakistan' },
  { city: 'Karachi',         country: 'Pakistan' },
  { city: 'Dhaka',           country: 'Bangladesh' },
  { city: 'Colombo',         country: 'Sri Lanka' },
  { city: 'Bangkok',         country: 'Thailand' },
  { city: 'Jakarta',         country: 'Indonesia' },
  { city: 'Kuala Lumpur',    country: 'Malaysia' },
  { city: 'Singapore',       country: 'Singapore' },
  { city: 'Manila',          country: 'Philippines' },
  { city: 'Hanoi',           country: 'Vietnam' },
  { city: 'Ho Chi Minh',     country: 'Vietnam' },
  { city: 'Yangon',          country: 'Myanmar' },
  { city: 'Phnom Penh',      country: 'Cambodia' },
  { city: 'Vientiane',       country: 'Laos' },
  { city: 'Taipei',          country: 'Taiwan' },
  { city: 'Hong Kong',       country: 'Hong Kong' },
  { city: 'Ulaanbaatar',     country: 'Mongolia' },
  { city: 'Tehran',          country: 'Iran' },
  { city: 'Baghdad',         country: 'Iraq' },
  { city: 'Riyadh',          country: 'Saudi Arabia' },
  { city: 'Dubai',           country: 'UAE' },
  { city: 'Abu Dhabi',       country: 'UAE' },
  { city: 'Jerusalem',       country: 'Israel' },
  { city: 'Tel Aviv',        country: 'Israel' },
  { city: 'Ankara',          country: 'Turkey' },
  { city: 'Istanbul',        country: 'Turkey' },
  { city: 'Tashkent',        country: 'Uzbekistan' },
  { city: 'Astana',          country: 'Kazakhstan' },
  { city: 'Almaty',          country: 'Kazakhstan' },
  { city: 'Tbilisi',         country: 'Georgia' },
  { city: 'Yerevan',         country: 'Armenia' },
  { city: 'Baku',            country: 'Azerbaijan' },
  { city: 'Kathmandu',       country: 'Nepal' },
  { city: 'Amman',           country: 'Jordan' },
  { city: 'Beirut',          country: 'Lebanon' },
  { city: 'Damascus',        country: 'Syria' },
  { city: 'Doha',            country: 'Qatar' },
  { city: 'Kuwait City',     country: 'Kuwait' },
  { city: 'Muscat',          country: 'Oman' },
  { city: 'Manama',          country: 'Bahrain' },
  { city: 'Kabul',           country: 'Afghanistan' },
  // Africa
  { city: 'Cairo',           country: 'Egypt' },
  { city: 'Alexandria',      country: 'Egypt' },
  { city: 'Nairobi',         country: 'Kenya' },
  { city: 'Lagos',           country: 'Nigeria' },
  { city: 'Abuja',           country: 'Nigeria' },
  { city: 'Johannesburg',    country: 'South Africa' },
  { city: 'Cape Town',       country: 'South Africa' },
  { city: 'Pretoria',        country: 'South Africa' },
  { city: 'Addis Ababa',     country: 'Ethiopia' },
  { city: 'Accra',           country: 'Ghana' },
  { city: 'Dakar',           country: 'Senegal' },
  { city: 'Casablanca',      country: 'Morocco' },
  { city: 'Rabat',           country: 'Morocco' },
  { city: 'Tunis',           country: 'Tunisia' },
  { city: 'Algiers',         country: 'Algeria' },
  { city: 'Tripoli',         country: 'Libya' },
  { city: 'Khartoum',        country: 'Sudan' },
  { city: 'Kinshasa',        country: 'DR Congo' },
  { city: 'Kampala',         country: 'Uganda' },
  { city: 'Dar es Salaam',   country: 'Tanzania' },
  { city: 'Lusaka',          country: 'Zambia' },
  { city: 'Harare',          country: 'Zimbabwe' },
  { city: 'Maputo',          country: 'Mozambique' },
  { city: 'Antananarivo',    country: 'Madagascar' },
  { city: 'Abidjan',         country: 'Ivory Coast' },
  { city: 'Luanda',          country: 'Angola' },
  // Oceania
  { city: 'Sydney',          country: 'Australia' },
  { city: 'Melbourne',       country: 'Australia' },
  { city: 'Canberra',        country: 'Australia' },
  { city: 'Brisbane',        country: 'Australia' },
  { city: 'Auckland',        country: 'New Zealand' },
  { city: 'Wellington',      country: 'New Zealand' },
]

/** Unique sorted country names derived from the location list */
export const COUNTRIES: string[] = Array.from(
  new Set(POPULAR_LOCATIONS.map(l => l.country))
).sort()

/** Title-case a string (first letter of each word capitalised) */
export function toTitleCase(s: string): string {
  return s.replace(/(?:^|\s)\S/g, c => c.toUpperCase())
}

/** Instant city+country search — returns up to 7 matches */
export function searchLocations(query: string): Location[] {
  const q = query.toLowerCase().trim()
  if (!q) return []
  return POPULAR_LOCATIONS.filter(
    l => l.city.toLowerCase().includes(q) || l.country.toLowerCase().includes(q)
  ).slice(0, 7)
}

/** Instant country-only search — returns up to 7 matches */
export function searchCountries(query: string): string[] {
  const q = query.toLowerCase().trim()
  if (!q) return []
  return COUNTRIES.filter(c => c.toLowerCase().includes(q)).slice(0, 7)
}
