export interface Ticker { symbol: string; name: string; type: string }

export const POPULAR_TICKERS: Ticker[] = [
  // US Large Cap
  { symbol: 'AAPL',  name: 'Apple Inc.',              type: 'Stock' },
  { symbol: 'MSFT',  name: 'Microsoft Corporation',   type: 'Stock' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.',            type: 'Stock' },
  { symbol: 'AMZN',  name: 'Amazon.com Inc.',          type: 'Stock' },
  { symbol: 'NVDA',  name: 'NVIDIA Corporation',       type: 'Stock' },
  { symbol: 'META',  name: 'Meta Platforms Inc.',      type: 'Stock' },
  { symbol: 'TSLA',  name: 'Tesla Inc.',               type: 'Stock' },
  { symbol: 'AVGO',  name: 'Broadcom Inc.',            type: 'Stock' },
  { symbol: 'JPM',   name: 'JPMorgan Chase & Co.',     type: 'Stock' },
  { symbol: 'V',     name: 'Visa Inc.',                type: 'Stock' },
  { symbol: 'WMT',   name: 'Walmart Inc.',             type: 'Stock' },
  { symbol: 'LLY',   name: 'Eli Lilly and Company',   type: 'Stock' },
  { symbol: 'MA',    name: 'Mastercard Inc.',          type: 'Stock' },
  { symbol: 'XOM',   name: 'Exxon Mobil Corporation', type: 'Stock' },
  { symbol: 'UNH',   name: 'UnitedHealth Group',       type: 'Stock' },
  { symbol: 'COST',  name: 'Costco Wholesale',         type: 'Stock' },
  { symbol: 'HD',    name: 'Home Depot Inc.',          type: 'Stock' },
  { symbol: 'PG',    name: 'Procter & Gamble Co.',     type: 'Stock' },
  { symbol: 'JNJ',   name: 'Johnson & Johnson',        type: 'Stock' },
  { symbol: 'ABBV',  name: 'AbbVie Inc.',              type: 'Stock' },
  { symbol: 'BAC',   name: 'Bank of America Corp.',    type: 'Stock' },
  { symbol: 'KO',    name: 'Coca-Cola Company',        type: 'Stock' },
  { symbol: 'MRK',   name: 'Merck & Co. Inc.',         type: 'Stock' },
  { symbol: 'CVX',   name: 'Chevron Corporation',      type: 'Stock' },
  { symbol: 'PEP',   name: 'PepsiCo Inc.',             type: 'Stock' },
  { symbol: 'ADBE',  name: 'Adobe Inc.',               type: 'Stock' },
  { symbol: 'AMD',   name: 'Advanced Micro Devices',   type: 'Stock' },
  { symbol: 'CRM',   name: 'Salesforce Inc.',          type: 'Stock' },
  { symbol: 'NFLX',  name: 'Netflix Inc.',             type: 'Stock' },
  { symbol: 'TMO',   name: 'Thermo Fisher Scientific', type: 'Stock' },
  { symbol: 'ORCL',  name: 'Oracle Corporation',       type: 'Stock' },
  { symbol: 'CSCO',  name: 'Cisco Systems Inc.',       type: 'Stock' },
  { symbol: 'INTC',  name: 'Intel Corporation',        type: 'Stock' },
  { symbol: 'IBM',   name: 'IBM Corporation',          type: 'Stock' },
  { symbol: 'GE',    name: 'GE Aerospace',             type: 'Stock' },
  { symbol: 'DIS',   name: 'Walt Disney Company',      type: 'Stock' },
  { symbol: 'NKE',   name: 'Nike Inc.',                type: 'Stock' },
  { symbol: 'PYPL',  name: 'PayPal Holdings Inc.',     type: 'Stock' },
  { symbol: 'UBER',  name: 'Uber Technologies Inc.',   type: 'Stock' },
  { symbol: 'LYFT',  name: 'Lyft Inc.',                type: 'Stock' },
  { symbol: 'SHOP',  name: 'Shopify Inc.',             type: 'Stock' },
  { symbol: 'SNAP',  name: 'Snap Inc.',                type: 'Stock' },
  { symbol: 'SPOT',  name: 'Spotify Technology',       type: 'Stock' },
  { symbol: 'PLTR',  name: 'Palantir Technologies',    type: 'Stock' },
  { symbol: 'AI',    name: 'C3.ai Inc.',               type: 'Stock' },
  { symbol: 'SMCI',  name: 'Super Micro Computer',     type: 'Stock' },
  { symbol: 'ARM',   name: 'Arm Holdings plc',         type: 'Stock' },
  { symbol: 'IONQ',  name: 'IonQ Inc.',                type: 'Stock' },
  { symbol: 'RGTI',  name: 'Rigetti Computing',        type: 'Stock' },
  { symbol: 'QBTS',  name: 'D-Wave Quantum Inc.',      type: 'Stock' },
  // Finance & Banks
  { symbol: 'GS',    name: 'Goldman Sachs Group',      type: 'Stock' },
  { symbol: 'MS',    name: 'Morgan Stanley',           type: 'Stock' },
  { symbol: 'WFC',   name: 'Wells Fargo & Company',    type: 'Stock' },
  { symbol: 'C',     name: 'Citigroup Inc.',           type: 'Stock' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway B',    type: 'Stock' },
  // Energy
  { symbol: 'NEE',   name: 'NextEra Energy Inc.',      type: 'Stock' },
  { symbol: 'OXY',   name: 'Occidental Petroleum',    type: 'Stock' },
  { symbol: 'SLB',   name: 'SLB (Schlumberger)',       type: 'Stock' },
  // ETFs
  { symbol: 'SPY',   name: 'SPDR S&P 500 ETF',        type: 'ETF' },
  { symbol: 'QQQ',   name: 'Invesco QQQ Trust',        type: 'ETF' },
  { symbol: 'DIA',   name: 'SPDR Dow Jones ETF',       type: 'ETF' },
  { symbol: 'IWM',   name: 'iShares Russell 2000 ETF', type: 'ETF' },
  { symbol: 'GLD',   name: 'SPDR Gold Shares ETF',     type: 'ETF' },
  { symbol: 'TLT',   name: 'iShares 20Y Treasury ETF', type: 'ETF' },
  { symbol: 'VTI',   name: 'Vanguard Total Market ETF',type: 'ETF' },
  // Indices
  { symbol: '^GSPC', name: 'S&P 500 Index',            type: 'Index' },
  { symbol: '^DJI',  name: 'Dow Jones Industrial',     type: 'Index' },
  { symbol: '^IXIC', name: 'NASDAQ Composite',         type: 'Index' },
  { symbol: '^VIX',  name: 'CBOE Volatility Index',    type: 'Index' },
  // Crypto
  { symbol: 'BTC-USD',  name: 'Bitcoin',               type: 'Crypto' },
  { symbol: 'ETH-USD',  name: 'Ethereum',              type: 'Crypto' },
  { symbol: 'BNB-USD',  name: 'BNB',                   type: 'Crypto' },
  { symbol: 'SOL-USD',  name: 'Solana',                type: 'Crypto' },
  { symbol: 'XRP-USD',  name: 'XRP',                   type: 'Crypto' },
  { symbol: 'ADA-USD',  name: 'Cardano',               type: 'Crypto' },
  { symbol: 'DOGE-USD', name: 'Dogecoin',              type: 'Crypto' },
  { symbol: 'DOT-USD',  name: 'Polkadot',              type: 'Crypto' },
  { symbol: 'LINK-USD', name: 'Chainlink',             type: 'Crypto' },
  { symbol: 'AVAX-USD', name: 'Avalanche',             type: 'Crypto' },
  { symbol: 'MATIC-USD',name: 'Polygon',               type: 'Crypto' },
  { symbol: 'UNI-USD',  name: 'Uniswap',              type: 'Crypto' },
  { symbol: 'SHIB-USD', name: 'Shiba Inu',             type: 'Crypto' },
  { symbol: 'LTC-USD',  name: 'Litecoin',              type: 'Crypto' },
  { symbol: 'ALGO-USD', name: 'Algorand',              type: 'Crypto' },
  // Commodities — Precious Metals
  { symbol: 'GC=F',    name: 'Gold Futures',           type: 'Commodity' },
  { symbol: 'SI=F',    name: 'Silver Futures',         type: 'Commodity' },
  { symbol: 'HG=F',    name: 'Copper Futures',         type: 'Commodity' },
  { symbol: 'PL=F',    name: 'Platinum Futures',       type: 'Commodity' },
  { symbol: 'PA=F',    name: 'Palladium Futures',      type: 'Commodity' },
  // Commodities — Energy
  { symbol: 'CL=F',    name: 'Crude Oil WTI',          type: 'Commodity' },
  { symbol: 'BZ=F',    name: 'Brent Crude Oil',        type: 'Commodity' },
  { symbol: 'NG=F',    name: 'Natural Gas',            type: 'Commodity' },
  { symbol: 'RB=F',    name: 'Gasoline Futures',       type: 'Commodity' },
  { symbol: 'HO=F',    name: 'Heating Oil Futures',    type: 'Commodity' },
  // Commodities — Agriculture
  { symbol: 'ZW=F',    name: 'Wheat Futures',          type: 'Commodity' },
  { symbol: 'ZC=F',    name: 'Corn Futures',           type: 'Commodity' },
  { symbol: 'ZS=F',    name: 'Soybean Futures',        type: 'Commodity' },
  // Forex — vs USD
  { symbol: 'EURUSD=X', name: 'Euro / US Dollar',      type: 'Forex' },
  { symbol: 'GBPUSD=X', name: 'British Pound / USD',   type: 'Forex' },
  { symbol: 'USDJPY=X', name: 'USD / Japanese Yen',    type: 'Forex' },
  { symbol: 'USDCAD=X', name: 'USD / Canadian Dollar', type: 'Forex' },
  { symbol: 'USDCHF=X', name: 'USD / Swiss Franc',     type: 'Forex' },
  { symbol: 'AUDUSD=X', name: 'Australian Dollar / USD',type: 'Forex' },
  { symbol: 'NZDUSD=X', name: 'New Zealand Dollar / USD',type: 'Forex' },
  { symbol: 'USDPLN=X', name: 'USD / Polish Zloty',    type: 'Forex' },
  { symbol: 'EURPLN=X', name: 'Euro / Polish Zloty',   type: 'Forex' },
  { symbol: 'USDMXN=X', name: 'USD / Mexican Peso',    type: 'Forex' },
  { symbol: 'USDINR=X', name: 'USD / Indian Rupee',    type: 'Forex' },
  { symbol: 'USDCNY=X', name: 'USD / Chinese Yuan',    type: 'Forex' },
  { symbol: 'USDBRL=X', name: 'USD / Brazilian Real',  type: 'Forex' },
  { symbol: 'USDHKD=X', name: 'USD / Hong Kong Dollar',type: 'Forex' },
  { symbol: 'USDSGD=X', name: 'USD / Singapore Dollar',type: 'Forex' },
  { symbol: 'USDNOK=X', name: 'USD / Norwegian Krone', type: 'Forex' },
  { symbol: 'USDSEK=X', name: 'USD / Swedish Krona',   type: 'Forex' },
]

export function searchLocal(query: string): Ticker[] {
  const q = query.toLowerCase().trim()
  if (!q) return []
  return POPULAR_TICKERS.filter(t =>
    t.symbol.toLowerCase().includes(q) ||
    t.name.toLowerCase().includes(q)
  ).slice(0, 7)
}
